### ISSUE TITLE
Support lastz Sequence Specifiers

### ISSUE THREAD

**Issue by iimog** [AliTVTeam/AliTV-perl-interface#152]
It is possible to provide lastz sequence specifiers: http://www.bx.psu.edu/miller_lab/dist/README.lastz-1.02.00/README.lastz-1.02.00a.html#seq_spec
Those are added to the filename in square brackets. A real world use case is to specify `unmask` to allow for lowercase letters in the fasta files. Otherwise those are treated as masked and ignored in the seeding stage. So fasta files with only lowercase letters will produce no alignments at all.
Unfortunately, it is not possible to provide those specifiers as normal parameters. So the current yml format is not sufficient. Actually, there is currently no way to get `unmask` behavior so the input files need to be changed.

**Comment by iimog** [comment]
If you want to change all nucleotides in all `.fa` files in a folder to uppercase you can use this command. Warning: this will change the files in place so only do this if the case does not carry information (e.g. masking) or do it on copies.
```
perl -i -pe 'tr/acgt/ACGT/ unless(/^>/)' *.fa
```

**Comment by Brunox13** [comment]
Oh wow. I just spent a few hours trying to figure out why my JSON file was always successfully created but showing nothing in the online visualization tool. I am creating my JSON file using the "simple" method where I provide the FASTA files directly, which is why I never read the [Description of the YML file format](Description of the YML file format) section, which contains the following CRUCIAL yet parenthetical note:

> (beware that lowercase letters in fasta files are treated as masked by lastz, see [issue#152](https://github.com/AliTVTeam/AliTV-perl-interface/issues/152) for details)

Therefore, PLEASE, put this note more visibly and higher on the documentation page so that is it encountered also by people who do not provide the YML file, so they don't waste their time like I did!!!
Thank you.

**Comment by iimog** [comment]
Hi @Brunox13,
thanks for letting us know about your struggles with this particular problem. I'm not happy with this default behavior of `lastz` and I agree that this important piece of information is somewhat hidden in the documentation. I'll put a prominent disclaimer into the main README file.
